mapWidth: 103
mapHeight: 52
output: "../myWorld/warehouse_24x15.map"
stationConfig: "picking_station.txt"
stationNumber: 1000
storageSize: [3,2]  # (width, height)
stationDistance: 2     # distance between two consecutive emitters
corridorWidth: 1    # distance between two storage blocks
pillarWidth: 3  # width of the pillar
operWidth: 1  # distance between the pickup station and the storage area

#for m,n (width,height) grid:
#width = 8 + m * 4 - 1
#height = 8 + n * 3 - 1
